MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
NKRO_ENABLE = yes
SPLIT_KEYBOARD = yes
# Special commands for Elite-Pi compatibility
BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040