#include "rgb.h"

LED_LIST_WASD[] = { LED_W, LED_A, LED_S, LED_D };
LED_LIST_WASD_SIZE = 4;

LED_LIST_ARROWS[] = { LED_LEFT, LED_RIGHT, LED_UP, LED_DOWN };
LED_LIST_ARROWS_SIZE = 4;

LED_LIST_FUNCROW[] = { LED_ESC, LED_F1, LED_F2, LED_F3, LED_F4, LED_F5, LED_F6, LED_F7, LED_F8, LED_F9, LED_F10, LED_F11, LED_F12, LED_PSCR};
LED_LIST_FUNCROW_SIZE = 14;

LED_LIST_NUMROW[] = { LED_GRV, LED_1, LED_2, LED_3, LED_4, LED_5, LED_6, LED_7, LED_8, LED_9, LED_0, LED_MINS, LED_EQL, LED_BSPC, LED_DEL};
LED_LIST_NUMROW_SIZE = 15;

LED_LIST_NUMPAD[] = {
    LED_U, LED_I, LED_O,
    LED_J, LED_K, LED_L,
    LED_M, LED_COMM, LED_DOT,
    LED_SPC, LED_RALT, LED_N, LED_B,
    LED_F12
    };
LED_LIST_NUMPAD_SIZE = 14;

LED_SIDE_LEFT[] = { LED_L1, LED_L2, LED_L3, LED_L4, LED_L5, LED_L6, LED_L7, LED_L8};
LED_SIDE_LEFT_SIZE = 8;

LED_SIDE_RIGHT[] = { LED_R1, LED_R2, LED_R3, LED_R4, LED_R5, LED_R6, LED_R7, LED_R8};
LED_SIDE_RIGHT_SIZE = 8;

LED_LIST_IJKL[] = {LED_I, LED_J, LED_K, LED_L};
LED_LIST_IJKL_SIZE = 4;
